name: Build AMI in feature branch

on: # yamllint disable-line rule:truthy
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build_ami:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.PACKER_ROLE_ARN }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.14.2

      - name: Run `packer init`
        id: init
        run: "packer init src/"

      - name: Run `packer validate`
        id: validate
        run: |
          # get default VPC ID
          export PKR_VAR_vpc_id=$(aws ec2 describe-vpcs --filters Name=isDefault,Values=true --query 'Vpcs[0].VpcId' --output text)
          
          # get a subnet ID in the default VPC
          export PKR_VAR_subnet_id=$(aws ec2 describe-subnets --filters Name=vpc-id,Values=${DEFAULT_VPC_ID} --query 'Subnets[0].SubnetId' --output text)
          
          # get CIDR block of the default VPC
          export PKR_VAR_ingress_cidrs="[\"$(aws ec2 describe-vpcs --vpc-ids ${DEFAULT_VPC_ID} --query 'Vpcs[0].CidrBlock' --output text)]\"]"
          
          export PKR_VAR_aws_region="eu-central-1"
          
          packer validate src/

      - name: Build Artifact
        run: packer build -on-error=abort src/
